name: CI - JMeter Performance Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:  # 👈 allows manual trigger

jobs:
  run-jmeter:
    runs-on: self-hosted  # Assumes this is a Windows runner with JMeter installed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run GMO-Auto Test
        run: |
          "D:\apache-jmeter-5.4.3\bin\jmeter.bat" -n -t jmeter-tests\GMO-Auto.jmx -l results\gmo-results.jtl -e -o results\gmo-report
        shell: cmd

      # - name: Run JPetStore Test
      # run: |
      #   "D:\apache-jmeter-5.4.3\bin\jmeter.bat" -n -t jmeter-tests\JPetStore.jmx -l results\jpetstore-results.jtl -e -o results\jpetstore-report
      # shell: cmd

      - name: Upload GMO-Auto Report
        uses: actions/upload-artifact@v3
        with:
          name: gmo-auto-report
          path: results/gmo-report

      # - name: Upload JPetStore Report
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: jpetstore-report
      #    path: results/jpetstore-report